import turtle
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.penup()
turtle.forward(50)

turtle.pendown()
turtle.forward(60)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(60)
turtle.penup()
turtle.forward(50)

turtle.pendown()
turtle.forward(60)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(30)
turtle.left(180)
turtle.forward(30)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(60)

turtle.exitonclick()